/**
 * Generates docs/CHARACTER_MAP.md from the actual presets, metadata and build output, so the map
 * can never drift from the implementation. Run: npm run map
 */
import { writeFileSync } from 'node:fs';
import { createServer } from 'vite';

const server = await createServer({ server: { middlewareMode: true }, appType: 'custom', logLevel: 'error' });
const { buildCharacter } = await server.ssrLoadModule('/src/character/build.js');
const { PRESETS, PRESET_META } = await server.ssrLoadModule('/src/character/presets/index.js');
const { CLIP_NAMES } = await server.ssrLoadModule('/src/anim/clips.js');

const swatch = (hex) => (hex ? `\`${hex}\`` : '—');
const lines = ['# Character Map', '', '_Generated by `scripts/character-map.mjs` from `src/character/presets/*.json`, `meta.json` and a real build. Do not edit by hand._', ''];
lines.push('| Character | Status | Height (range) | Age (range) | Build / muscle | Tris | Draws | Tex KB |', '|---|---|---|---|---|---|---|---|');
const rows = [];
for (const p of PRESETS) {
  const g = buildCharacter(p);
  const s = g.userData.stats;
  const d = g.userData.definition;
  const m = PRESET_META[p.id] ?? {};
  rows.push({ p, d, s, m });
  lines.push(`| **${d.name}** (\`${d.id}\`) | ${m.status ?? '—'} | ${d.body.height.toFixed(2)} m (${(m.heightRange ?? []).join('–')}) | ${d.body.age} (${(m.ageRange ?? []).join('–')}) | ${d.body.build} / ${d.body.muscle} | ${s.triangles} | ${s.drawCalls} | ${Math.round(s.textureBytes / 1024)} |`);
}
lines.push('');
for (const { d, m } of rows) {
  const acc = d.accessories.map((a) => a.type).join(', ') || 'none';
  lines.push(`## ${d.name}`, '', `${m.identity ?? ''}`, '');
  lines.push(`- **Visual goals:** ${(m.visualGoals ?? []).join('; ')}`);
  lines.push(`- **Proportions:** height ${d.body.height} m, build ${d.body.build}, muscle ${d.body.muscle}, shoulders ${d.body.shoulders}, hips ${d.body.hips}, legs ${d.body.legLength}, arms ${d.body.armLength}, head ${d.body.headSize}`);
  lines.push(`- **Face preset:** ${d.face.preset}${d.face.facialHair && d.face.facialHair !== 'none' ? ` + ${d.face.facialHair}` : ''}`);
  lines.push(`- **Hair:** ${d.hair.style} ${swatch(d.hair.color)}`);
  lines.push(`- **Skin:** ${swatch(d.skin.tone)}; tattoos L=${d.tattoos.left} R=${d.tattoos.right}`);
  lines.push(`- **Top:** ${d.top ? `${d.top.type} ${swatch(d.top.color)} (fit ${d.top.fit}, sleeve ${d.top.sleeve})` : 'none'}${d.outer ? `; outer: ${d.outer.type} ${swatch(d.outer.color)}` : ''}`);
  lines.push(`- **Bottom:** ${d.bottom ? `${d.bottom.type} ${d.bottom.kind} ${d.bottom.length} ${swatch(d.bottom.color)}${d.bottom.belt ? ' + belt' : ''}` : 'none'}`);
  lines.push(`- **Shoes:** ${d.shoes.type} ${swatch(d.shoes.upper)} / ${swatch(d.shoes.sole)}; **Accessories:** ${acc}`);
  lines.push(`- **Animation profile:** ${m.animationProfile ?? 'baseline'}; clips: ${CLIP_NAMES.length} shared (${CLIP_NAMES.join(', ')})`);
  lines.push(`- **Rig:** ${d.rig} (shared canonical skeleton, UniMate joint names)`);
  lines.push(`- **Known issues:** ${(m.knownIssues ?? []).join('; ') || 'none logged'}`);
  lines.push(`- **Final polish:** ${(m.polish ?? []).join('; ') || '—'}`, '');
}
writeFileSync('docs/CHARACTER_MAP.md', lines.join('\n'));
console.log(`CHARACTER_MAP.md: ${rows.length} characters`);
await server.close();
